### ISSUE TITLE
Use playerdb.co over mcuuid.net scraping

### ISSUE THREAD

**Issue by Cherry** [tycrek/McServerman#2]
Hey! I'm with Nodecraft, and my team and I maintain https://mcuuid.net, https://playerdb.co and https://mcversions.net.

This project looks really cool! It's always great to see more and more tools being created to manage Minecraft servers.

I'd heavily recommend that you switch to using https://playerdb.co to retrieve player information instead of scraping https://mcuuid.net though in https://github.com/tycrek/McServerman/blob/557b70a46e6f6d0a63d4dd65eca7d5e6673b7886/app.js#L109

MCUUID's page layout may change at any time, whereas the playerdb.co API is stable, and should actually improve performance for your app too as it won't have to parse HTML.

In addition, I'd advise against scraping https://mcversions.net too for the same reasons. Mojang publish this data at https://launchermeta.mojang.com/mc/game/version_manifest.json, or if you really want to use our nicer formatted version, https://mcversions.net/mcversions.json - again do note that this may change at any point though.

**Comment by tycrek** [comment]
Thank you so much for this information! I had been looking for API's or computer-friendly data for those but was having a hard time so this is much appreciated. I'll leave this open for now but either later today or tomorrow I can update it.

**Comment by tycrek** [comment]
@Cherry I've updated the player UUID function and can confirm that it works. Having JSON responses with proper errors/success messages is much better than parsing HTML.

As for the versions, I'm thinking of having the software download a local copy of `mcversions.json` and then updating it every 6 hours or so (as well as when the software is launched). The formatting is much nicer than Mojang's JSON, and having a local copy would reduce the amount of calls to your server. What are your thoughts on this?

**Comment by Cherry** [comment]
Awesome! We use that API internally heavily and cache responses on Cloudflare’s edge, so the more people that use it, the faster it’ll be! 🎉

As for the MCVersions data, don’t worry about hitting our server. This is again stored and cached on Cloudflare’s edge with Workers, and we have a GitHub action that runs every hour to check for updates, and then pushes any updates to Cloudflare. The entire site is hosted with Cloudflare Workers.

I can’t promise that mcversions JSON file we produce will stay the same forever though, so just be aware of that.

**Comment by tycrek** [comment]
Thanks again @Cherry and Nodecraft!
